### ISSUE TITLE
v2

### ISSUE THREAD

**Issue by RWOverdijk** [RWOverdijk/AssetManager#132]
This is a general discussion for AssetManager V2. We'll be collecting things to be done and discuss them as well.
- [ ] Last modified https://github.com/RWOverdijk/AssetManager/pull/130
- [ ] @iwalz collection https://github.com/RWOverdijk/AssetManager/pull/75
- [ ] Cache warmup https://github.com/RWOverdijk/AssetManager/issues/40
- [ ] Static file cache https://github.com/RWOverdijk/AssetManager/issues/76
- [ ] Serving collections and naming of config keys https://github.com/RWOverdijk/AssetManager/issues/102
- [ ] Serving hash-based https://github.com/RWOverdijk/AssetManager/issues/99
- [ ] Safe names (is this actually an issue?) https://github.com/RWOverdijk/AssetManager/issues/107
- [ ] Better filters https://github.com/RWOverdijk/AssetManager/issues/109
- [ ] Filters and collections https://github.com/RWOverdijk/AssetManager/issues/110
- [ ] Resolvers shouldn't implement `setAggregateResolver`
- [ ] CDN / publish assets https://github.com/RWOverdijk/AssetManager/issues/131
- [ ] Wildcard cache https://github.com/RWOverdijk/AssetManager/issues/121
- [ ] Wildcards in general

**Comment by spiffyjr** [comment]
I didn't see this on your check list but a nice way to manage debug mode which removes filters and expands collections would be nice. That would require some sort of view helper, I think, so that when you output a collection in debug mode it really includes multiple script lines.

**Comment by RWOverdijk** [comment]
@spiffyjr You'd use your local config for that.

**Comment by wshafer** [comment]
Ok I've gone through all the issues/pr's and this list and created a list of things I'm willing to tackle for a V2.

Please take a look and let me know if this list is adequate and if there's anything else you'd to see added.

https://github.com/wshafer/assetmanager-core/issues

**Comment by RWOverdijk** [comment]
@wshafer Comprehensive and contains the most important tasks in my opinion. 👍

**Comment by RWOverdijk** [comment]
There's a v2 now, because Laminas.

Let's at least close this.
